### ISSUE TITLE
Error while reloading

### ISSUE THREAD

**Issue by meNeither** [textmate/todo.tmbundle#10]
> Exception thrown while reading data: *** -[NSConcreteFileHandle fileDescriptor]: unknown error.

is thrown, if you reload the TODO window via context menu -> Reload.

I don't know, if reloading is an intended feature, but it would be a nice enhancement. :)

**Comment by infininight** [comment]
Yeah, this would have to be a TextMate feature to rerun the command when invoked. Since it would be a Textmate feature I'm going to close this issue but it's not a bad idea thanks!
