### ISSUE TITLE
Change layout of options

### ISSUE THREAD

**Issue by sorbits** [textmate/todo.tmbundle#2]
I think presenting the options like:

```
Filter: [                ]
        [ ] Show path info
```

Is more inline with OS X layout conventions.

**Comment by Soryu** [comment]
Original: http://dl.dropbox.com/u/2015714/textmate/todo/1%20original.png
Relayout: http://dl.dropbox.com/u/2015714/textmate/todo/2%20layout.png
Nicer spacing: http://dl.dropbox.com/u/2015714/textmate/todo/3%20spacing.png

What do you think?

**Comment by sorbits** [comment]
Definitely prefer “Nicer Spacing”.

**Comment by Soryu** [comment]
Right, just wanted to outline my way of getting there and the changes wrt the original to compare “wasted” vertical space. Do you think the input field should be longer? Maybe changing in size when the window gets wider?

**Comment by sorbits** [comment]
I think it is wide enough and doesn’t look odd that it doesn’t extend to the right border (since it sort of follows the width of the text below) — so I’d be fine with the current static size.

**Comment by Soryu** [comment]
fixed.
