### ISSUE TITLE
Only works with projects (since recent commit)

### ISSUE THREAD

**Issue by sorbits** [textmate/todo.tmbundle#3]
This commit ac07daa573e3c8063569350d08f5880c7380bb26 reference `project_dir` in the ERb template.

When using _Show TODO_ in a single file this [cause an exception](http://lists.macromates.com/textmate/2009-November/030090.html).

**Comment by Soryu** [comment]
Fixed TODO list  when using on single files. “Show relative path” checkbox is disabled in that case.
