### ISSUE TITLE
cannot show todo list

### ISSUE THREAD

**Issue by pvinis** [textmate/todo.tmbundle#6]
i get this error with textmate 2(9307).  
`/Users/pvinis/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/escape.rb:23:in 'e_url': private method `gsub' called for nil:NilClass (NoMethodError)  
    from (erb):21:in 'header'  
    from /Users/pvinis/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/tm/htmloutput.rb:91:in 'header'  
    from /Users/pvinis/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/web_preview.rb:4:in 'html_head'  
    from /Users/pvinis/Library/Application Support/TextMate/Managed/Bundles/TODO.tmbundle/Support/todo.rb:63`

**Comment by infininight** [comment]
Have you customized your installed version of ruby?

**Comment by pvinis** [comment]
i tried with the default system ruby (1.8.7), and i tried with 1.9.3. both had problems.

**Comment by sorbits** [comment]
If this is still relevant then see https://github.com/textmate/textmate/wiki/Reverting-To-Defaults
